language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t thirteen/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true thirteen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-788241664327"
  bucket_path: "docker-test"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"